---
# Global configuration
data_path:   '/users/yan/dev-local/data'
output_path: '/users/yan/dev-local/output'
interfaces:  ['Biopac', 'BeGaze']

# List of recognized tasks and their interface configurations
tasks:
  Calibration:
    ID: 1
    interfaces:
      BeGaze:
        files:
          samples: '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>1)_(S|s)amples\.txt$'
          labels:  '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>1)_labels\.txt$'
        labels:
          GreyFix:  [10000, 1, 'BlackFix(?P<Event_ID>[0-9]+)']
          BlackFix: [10000, 1,  'GreyFix(?P<Event_ID>[0-9]+)']
          WhiteFix: [10000, 1, 'WhiteFix(?P<Event_ID>[0-9]+)']
      Biopac:
        files: '(Calibration|Calibrate)_(?P<Subject_ID>[0-9]{3})(?P<Task_Order>1)(_[0-9]{4}|)\.mat$'
        labels:
          SixMinFix: [360000, 1, 'SixMinFix']
  Eyemotion:
    ID: 2
    interfaces:
      BeGaze:
        files:
          samples: '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_(S|s)amples\.txt$'
          labels: '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_labels\.txt$'
        labels:
          InitialFix: [8000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_InitialFix']
          ShortStim:  [2000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_ShortStim' ]
          Fix2:       [3000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_Fix2'      ]
          PreCueStim: [2000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_PreCueStim']
          ImgwCue:    [1000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_ImgwCue'   ]
          LongStim:   [8000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>Attend|Rethink|Distract)_LongStim'  ]
        # ROI:
        #   - path: '/Users/yan/dev-local/data/roi/henry2'
        #     files: '^(?P<Event_ID>[0-9\.]+)\w*\.(bmp)$'
        #     color: [ 30, 255,  0]
        #   - path: '/users/yan/dev-local/data/roi/ko2'
        #     files: '^(?P<Event_ID>[0-9\.]+)\w*\.(bmp)$'
        #     color: [ 30, 255,  0]
      Biopac:
        files: 'Eye(M|m)otion_(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])(_[0-9]{4}|)\.mat$'
  Sternberg:
    ID: 3
    interfaces:
      BeGaze:
        files:
          samples: '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_(S|s)amples\.txt$'
          labels:  '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_labels\.txt$'
        labels:
          ShortStringEncoding: [1200, 2, 'ShortString_(?P<Event_Group>Absent|Present)_(?P<Event_ID>^[0-9\.]+)']
          ShortStringFixation: [3000, 2, 'ShortString_(?P<Event_Group>Absent|Present)_(?P<Event_ID>^[0-9\.]+)Fix2']
          LongStringEncoding:  [3600, 2,  'LongString_(?P<Event_Group>Absent|Present)_(?P<Event_ID>^[0-9\.]+)']
          LongStringFixation:  [3000, 2,  'LongString_(?P<Event_Group>Absent|Present)_(?P<Event_ID>^[0-9\.]+)Fix1']
      Biopac:
        files: 'Sternberg_(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])(_[0-9]{4}|)\.mat$'
  Slideshow:
    ID: 4
    interfaces:
      BeGaze:
        files:
          samples: '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_(S|s)amples\.txt$'
          labels:  '^(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])_labels\.txt$'
        labels:
          InitialFix: [3000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>pos|neutral|neg)_InitialFix']
          LongStim:   [8000, 2, '(?P<Event_ID>^[0-9\.]+)_(?P<Event_Group>pos|neutral|neg)_InitialFix']
        # ROI:
        #   - path: '/Users/yan/dev-local/data/roi/henry'
        #     files: '^(?P<Event_ID>[0-9\.]+)\w*\.(bmp)$'
        #     color: [  0,   0,  0]
        #   - path: '/users/yan/dev-local/data/roi/ko'
        #     files: '^(?P<Event_ID>[0-9\.]+)\w*\.(bmp)$'
        #     color: [ 30, 255,  0]
      Biopac:
        files: '(Slideshow|EmoSlideshow)_(?P<Subject_ID>[0-9]{3})(?P<Task_Order>[2-4])(_[0-9]{4}|)\.mat$'